version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
