version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
      day: saturday
