# These are supported funding model platforms

# github: [JamzumSum] # Replace with up to 4 GitHub Sponsors-enabled usernames
custom: # Replace with up to 4 custom sponsorship URLs
  - https://qr.alipay.com/fkx10234cmr6fa52pbochc7
