# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: uv run ruff check --select I --fix
        pass_filenames: false
        language: system
        types: [python]
      - id: black
        name: Black
        entry: uv run ruff format
        pass_filenames: false
        language: system
        types: [python]
      # - id: pytest
      #   name: pytest-check
      #   entry: uv run pytest test
      #   language: system
      #   pass_filenames: false
      #   types: [python]
default_language_version:
  python: python3
