version: "2"
services:
  qzone:
    container_name: qzone
    image: jamzumsum/qzone2tg:latest
    restart: always
    environment:
      DBUS_SESSION_BUS_ADDRESS: ${DBUS_SESSION_BUS_ADDRESS}
    volumes:
      - ${DBUS_SESSION_BUS_ADDRESS}:${DBUS_SESSION_BUS_ADDRESS}:ro
      - $PWD/config/config.yaml:/app/config/config.yaml:ro
      - $PWD/data:/app/data
    # privileged: true
    # enable privilege mode only if using root

  # remove the following service if you needn't reverse proxy. 
  # nginx:
  #   container_name: qz_reverse_proxy
  #   image: nginx
  #   ports:
  #     - 443:443
  #   links:
  #     - qzone
  #   depends_on:
  #     - qzone
  #   restart: always
  #   volumes:
  #     - $PWD/config/nginx.conf:/etc/nginx/nginx.conf:ro
