[project]
name = "Qzone3TG"
version = "0.9.11.dev2"
description = "Forward Qzone feeds to telegram."
authors = [{ name = "aioqzone" }]
maintainers = [
    { name = "JamzumSum", email = "22952836+JamzumSum@users.noreply.github.com" },
]
readme = "README.md"
license = { text = "AGPL-3.0" }
requires-python = "~=3.13.0"
dependencies = [
    "aioqzone-feed>=1.3.1.dev1,<2.0.0",
    "qzemoji>=6.1.0",
    "aiogram[proxy]>=3.3.0,<4.0.0",
    "apscheduler>=3.10.4,<4.0.0",
]

[project.urls]
"Repository" = "https://github.com/aioqzone/Qzone2TG"
"Documentation" = "https://aioqzone.github.io/Qzone2TG"

[project.optional-dependencies]
slide-captcha = ["aioqzone-feed[slide-captcha]"]

[dependency-groups]
dev = ["pre-commit", "ruff"]
test = ["pytest>=8.2.1,<9.0.0", "pytest-asyncio~=0.26.0"]
doc = [
    "Sphinx>=8.0.2,<9.0.0",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints>=2.2.0,<3.0.0",
    "furo>=2024.8.6",
    "sphinx-design>=0.6.1,<1.0.0",
]

[tool.uv.sources]
aioqzone-feed = { index = "aioqzone-index" }

[[tool.uv.index]]
name = "aioqzone-index"
url = "https://aioqzone.github.io/aioqzone-index/simple/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
log_cli_level = 'WARNING'
pythonpath = 'src'
log_cli = true

[tool.ruff]
line-length = 99

[tool.pyright]
pythonVersion = "3.13"
pythonPlatform = "All"
