[tool.poetry]
name = "Qzone3TG"
version = "0.5.0a7.dev2"
description = "Forward Qzone feeds to telegram."
authors = ["aioqzone <zzzzss990315@gmail.com>"]
readme = "README.md"
license = "AGPL-3.0"
homepage = "https://github.com/aioqzone/Qzone2TG"
repository = "https://github.com/aioqzone/Qzone2TG"
documentation = "https://aioqzone.github.io/Qzone2TG"

[tool.poetry.dependencies]
python = "~3.10.2"
aioqzone-feed = { url = "https://github.com/aioqzone/aioqzone-feed/releases/download/0.9.4a1.dev1/aioqzone_feed-0.9.4a1.dev1-py3-none-any.whl" }
python-telegram-bot = { extras = ["socks", "rate-limiter"], version = "^20.0a4" }
httpx = { version = "~0.23.0" }
socksio = { git = "https://github.com/JamzumSum/socksio.git", rev = "master" }


# dependency groups
[tool.poetry.group.test]
optional = false

[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"
pytest-asyncio = "~0.19.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.19.0"
black = "^22.1.0"
isort = "^5.10.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"
autodoc-pydantic = "^1.7.0"
sphinx-autodoc-typehints = "^1.18.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-tabs = "^3.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
markers = [
    "needuser: Need user interaction, DO NOT use in ci",
    "incremental: xfail succ cases if pred case failed or skipped",
    "upstream: Test cannot run normally due to upstream problems",
]
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'


[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
target-version = ['py310']
