[tool.poetry]
name = "Qzone3TG"
version = "0.4.0a1.dev3"
description = "Forward Qzone feeds to telegram."
authors = ["aioqzone <zzzzss990315@gmail.com>"]
readme = "README.md"
license = "AGPL-3.0"
homepage = "https://github.com/aioqzone/Qzone2TG"
repository = "https://github.com/aioqzone/Qzone2TG"
documentation = "https://aioqzone.github.io/Qzone2TG"

[tool.poetry.dependencies]
python = "~3.10.2"
aioqzone-feed = {git = "https://github.com/aioqzone/aioqzone-feed.git", rev = "beta"}
python-telegram-bot = {extras = ["socks"], version = "^13.13"}
httpx = {version = "^0.23.0", extras = ["socks"]}
# extras: dev
pre-commit = {version = "^2.19.0", optional = true}
black = {version = "^22.1.0", optional = true}
isort = {version = "^5.10.1", optional = true}
# extras: doc
Sphinx = {version = "^4.5.0", optional = true}
autodoc-pydantic = {version = "^1.7.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.18.2", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
sphinx-tabs = {version = "^3.3.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.18.2"

[tool.poetry.extras]
dev = [
    "pre-commit",
    "black",
    "isort"
]
doc = [
    "Sphinx",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "sphinx-tabs"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
markers = [
    "needuser: Need user interaction, DO NOT use in ci",
    "incremental: xfail succ cases if pred case failed or skipped",
    "upstream: Test cannot run normally due to upstream problems",
]
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'


[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
target-version = ['py310']
