[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
markers = [
    "needuser: Need user interaction, DO NOT use in ci",
    "incremental: xfail succ cases if pred case failed or skipped.",
]
asyncio_mode = 'strict'

[tool.isort]
profile = "google"
