REPO = "https://github.com/aioqzone/Qzone2TG"
DISCUSS = "https://t.me/qzone2tg_discuss"
CHANNEL = "https://t.me/qzone2tg"
DOCUMENT = "https://aioqzone.github.io/Qzone2TG"
AGREEMENT = "https://github.com/aioqzone/Qzone2TG/blob/beta/README.zh-cn.md#license"
