# This compose yaml is for starting up qzone3tg container.
# Substitute any environment variables on demand;
# or a .env file in docker folder is okay.
version: "3"
services:
  qzone:
    container_name: qzone
    image: qzone3tg:latest  # ghcr.io/JamzumSum/qzone3tg:latest
    environment:
      password: ${PASSWD}
      token: ${TOKEN}
      log.conf: config/log.ini
      qzone.qq: ${UIN}
      bot.admin: ${ADMIN}
      bot.storage.database: data/${UIN}.db
      # bot.network.proxy: socks5h://host.docker.internal:7890
    network_mode: host
    volumes:
      - ../config:/app/config:ro
      - qzone-data:/app/data
      # - ../data:/app/data   # choose a syntax as you like
volumes:
  qzone-data:
