services:
  qzone:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      network: host
    container_name: app
    image: qzone3tg:${QZONE3TG_VERSION} # ghcr.io/jamzumsum/qzone3tg:latest
    network_mode: host    # add/remove this on demand
    secrets:
    - source: qzone_password
      target: password
    - source: telegram_bot_token
      target: token
    volumes:
    - type: volume
      source: qzone-data
      target: /app/data
    - ../config:/app/config:ro
volumes:
  qzone-data:
    name: qzone-data
secrets:
  qzone_password:
    name: qzone_password
    file: ../config/secrets/password
  telegram_bot_token:
    name: telegram_bot_token
    file: ../config/secrets/token
