version: "3"
services:
  qzone:
    container_name: qzone
    image: ghcr.io/jamzumsum/qzone3tg:latest
    environment:
      # 您可以直接将下列配置中的变量替换为实际值
      # 也可以在 docker 目录中新建 .env 文件并定义这些变量。
      password: ${PASSWD}
      token: ${TOKEN}
      log.conf: config/log.ini
      qzone.qq: ${UIN}
      bot.admin: ${ADMIN}
      bot.storage.database: data/${UIN}.db
      # bot.network.proxy: socks5h://host.docker.internal:7890
    network_mode: host
    volumes:
      - ../config:/app/config:ro
      - qzone-data:/app/data
      # - ../data:/app/data   # choose a syntax as you like
      # - ../log:/app/log
volumes:
  qzone-data:
