log:
  level: warning
  
bot:
  accept_id: ${oc.env:TEST_ACCEPTID}
  method: polling
  token: ${oc.env:TEST_BOT_TOKEN}
  daily: "12:00"

feed:
  keepdays: 0

qzone:
  UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
  fetch_times: 12
  qq: ${oc.env:TEST_UIN}
  qr_strategy: forbid
