# This workflow builds docker image and pushes it.

name: Build and Release

on:
  workflow_call:
    inputs:
      VERSION_TAG:
        required: true
        type: string

jobs:
  build-release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          file: ./docker/Dockerfile
          tags: |
            qzone3tg:${{ inputs.VERSION_TAG }}
            qzone3tg:latest
          build-args: |
            ${{ jobs.build-release-pkg.outputs.version }}
