# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dev CI

on:
  push:
    paths:
      - "src/qzone3tg/**"
      - "test/**"
      - ".github/workflows/test.yml"
      - ".github/workflows/ci.yml"
      - "poetry.lock"
      - "package-lock.json"
    branches:
      - dev
      - dev/**

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    if: "!contains(github.event.head_commit.message, '@no-test')"
    with:
      PYTEST_ARGS: test
    secrets:
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}

  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        if: "!contains(github.event.head_commit.message, '@no-pr')"
        with:
          destination_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_body: ${{ github.event.head_commit.message }} # only push event has head_commit
