# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dev CI

on:
  push:
    paths:
      - "src/qzone3tg/**"
      - "test/**"
      - ".github/workflows/test.yml"
      - ".github/workflows/ci.yml"
      - "poetry.lock"
      - "package-lock.json"
    branches:
      - dev
      - dev/**

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    if: "!contains(github.event.head_commit.message, '@no-test')"
    with:
      PYTEST_ARGS: test
    secrets:
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}

  merge:
    if: "!contains(github.event.head_commit.message, '@no-pr')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: beta
      - name: Get SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: -t ${{ needs.test.outputs.package-version }} ${{ steps.sha.outputs.sha }}..HEAD
        env:
          OUTPUT: CHANGELOG.md

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_template: ${{ steps.git-cliff.outputs.changelog }}
