# This workflow builds docker image and pushes it.

name: Build Docker Image

on:
  workflow_call:
    inputs:
      VERSION_TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      VERSION_TAG:
        description: "tag of the image"
        required: true
        type: string

permissions:
  packages: write

jobs:
  build-release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: |
            ghcr.io/qzone3tg:${{ inputs.VERSION_TAG || github.event.inputs.VERSION_TAG }}
            ghcr.io/qzone3tg:latest
