# This workflow builds docker image and pushes it.

name: Build Docker Image

on:
  workflow_call:
    inputs:
      VERSION_TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      VERSION_TAG:
        description: "tag of the image"
        required: true
        type: string
  pull_request_target:
    types:
      - closed
    branches:
      - beta

permissions:
  packages: write

jobs:
  build-release-docker:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target' || github.event.pull_request.merged == true && startsWith(github.head_ref, 'dev')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: |
            ghcr.io/aioqzone/qzone3tg:${{ inputs.VERSION_TAG || github.event.inputs.VERSION_TAG || github.event.pull_request.title }}
            ghcr.io/aioqzone/qzone3tg:latest
