name: '[docker] CI for releases'

on:
    push:
        branches: master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
            name: Build dockerfile (with push)
            env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                docker buildx build \
                --platform=linux/amd64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/qzone2tg:latest \
