# This workflow builds sphinx documents and deploy it.
name: Sphinx Build and Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - doc/**
      - ".github/workflows/sphinx.yml"
      # ci.yml will handle these pushes
      - "!src/**"
      - "!test/**"
      - "!poetry.lock"

jobs:
  sphinx-build-deploy:
    uses: JamzumSum/aioqzone/.github/workflows/sphinx.yml@beta
