# This workflow builds sphinx documents and deploy it.
name: Sphinx Build and Deploy

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - doc/**
      - ".github/workflows/sphinx.yml"

jobs:
  sphinx-build-deploy:
    uses: aioqzone/aioqzone/.github/workflows/sphinx.yml@beta
