# install dependency and current package
name: Test

on:
  pull_request:
    types:
      - review_requested
    branches:
      - beta
      - release

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install and Test
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
        run: |
          echo "::group::Install Dependencies"
          uv sync --no-default-groups --group test
          echo "::endgroup::"

          echo "::group::pytest outputs"
          uv run pytest test
          echo "::endgroup::"

      - name: Request Changes
        env:
          GH_TOKEN: ${{ secrets.COMMENT_PAT }} # the reviewer PAT
        run: |
          if [[ $GH_TOKEN != "" ]]; then
              gh pr review ${{ github.event.pull_request.number }} -r -b "Some test(s) failed."
          fi
