# install dependency and current package
name: Test

on:
  workflow_call:
    inputs:
      PYTEST_ARGS:
        required: true
        type: string
    secrets:
      TEST_TOKEN:
        required: true
      TEST_PASSWORD:
        required: true
    outputs:
      package-version:
        description: version of this python package output by poetry
        value: ${{ jobs.install-test.outputs.package-version }}


jobs:
  install-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    outputs:
      package-version:
        ${{ steps.version_step.outputs.package }}

    steps:
      #----------------------------------------------
      #   check-out repo and set-up node & python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Get Package Version
        id: version_step
        run: |
          echo "::set-output name=package::$(poetry version -s)"
      #----------------------------------------------
      #   install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install -n
      #----------------------------------------------
      #    add matrix specifics and run test suite
      #----------------------------------------------
      - name: Test with pytest
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          poetry run python -m pytest ${{ inputs.PYTEST_ARGS }}
